apiVersion: switches.lin.cn/v1
kind: EdgeSwitch
metadata:
  labels:
    app.kubernetes.io/name: app-operator
    app.kubernetes.io/managed-by: kustomize
  name: edgeswitch-sample
spec:
  # TODO(user): Add fields here
